version: ${VERSION}

services:
  mysql:
    image: mariadb:10.3
    container_name: mysql
    restart: always

    environment:      
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PORT: ${MYSQL_PORT}

    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
      - ./db.sql:/docker-entrypoint-initdb.d/2.sql:ro
    
  apache:
    build: .
    container_name: apache
    restart: always
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ./www:/var/www/html
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_ARBITARY=1
      - PMA_HOST=mysql
      - PMA_PORT=${MYSQL_PORT}